version: "3"
services:
  db:
    image: postgres:12.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: step-travel
    ports:
      - '3000:3000'
    environment:
      DB_NAME: step-travel-development
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    networks:
      - default
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle_install:/app/vendor/bundle
      - bundle:/app/.bundle
volumes:
  postgres-data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
